var a = "Hi"
var b = 2
var c = true
var e = 'test'
var a = 10
var b = 20
a+b ('adding with number is called as string')
30
a-b
-10
a*b
200
a/b
0.5
a%b

var a="Huzaifa"
var b= "is learning JavaScripit"
a+b ('adding with string is called a Concat')
'Huzaifais learning JavaScripit'
a-b
NaN  ( 'NaN full form is not a number')
a*b
NaN
a/b
NaN

"12"-1
11
"12"+2
'122'
10(a) +1
VM105:1 ()
"10"+10+10
'101010'
10+10
20
var a = true
undefined
var b = true
undefined
a+b
2
true
true
true+true
2
false
false
false+false
0
true-false
1
20+true
21
"true"+true
'truetrue'